# Type `isotracer --help` for all CLI options
# default rt window = 0.03 min
# default precmz ppm = 10 ppm
# configurable with --rttol and --mztol, respectively
CONDITIONS = ["ACE", "MET", "GLU", "PROP"]
SECONDARY = ["D0", "D3"]
INPUT = "SERY/"
NAME = "SERY"
TOL = 10
MINSCAN_SCRAPE = 1
MINSCAN_ANALYZE = 3
MINCOND = 1

rule all:
  input: "analyze.done"

rule validate:
  output: touch("validate.done")
  shell:
    "isotracer validate {INPUT} {CONDITIONS} -s {SECONDARY} -n {NAME}"

# default minreps = 3
rule prep:
  input: "validate.done"
  output: touch("prep.done")
  shell:
    "isotracer prep {INPUT} {CONDITIONS} -s {SECONDARY} -n {NAME} --mztol {TOL}"

# default minreps = 3
# `--retry` by default because assuming changes to config
# Remove this flag if you want to try continuing analysis
rule scrape:
  input: "prep.done"
  output: touch("scrape.done")
  shell:
    "isotracer scrape {INPUT} {CONDITIONS} -s {SECONDARY} --retry -n {NAME} --mztol {TOL} --minscans {MINSCAN_SCRAPE}"

# default minconditions = 1
rule analyze:
  input: "scrape.done"
  output: touch("analyze.done")
  shell:
    "isotracer analyze {INPUT} {CONDITIONS} -s {SECONDARY} -n {NAME} --minconditions {MINCOND} --minscans {MINSCAN_ANALYZE}"
