name : isoanalyst
channels :
  - defaults
  - conda-forge
  - bioconda
dependencies :
  - python>=3.8
  - pip
  - snakemake-minimal
  - joblib
  - numpy
  - pandas
  - rtree
  - scipy
  - pip:
    - pymzml