# Type `isoanalyst --help` for all CLI options
# default rt window = 0.03 min
# default precmz ppm = 10 ppm
# configurable with --rttol and --mztol, respectively
NAME = "EXAMPLE"
INPUT_SPEC = "input_spec.csv"
TOL = 10 # PPM
MINSCAN_SCRAPE = 1
MINSCAN_ANALYZE = 2
MINCOND = 1
MININTENSITY = 0

rule all:
  input: "analyze.done"

rule validate:
  output: touch("validate.done")
  shell:
    "isoanalyst validate -n {NAME} -i {INPUT_SPEC}"

# default minreps = 3
rule prep:
  input: "validate.done"
  output: touch("prep.done")
  shell:
    "isoanalyst prep -n {NAME} -i {INPUT_SPEC} --mztol {TOL} --minreps 1 --no-blank-remove"

# default minreps = 3
# `--retry` by default because assuming changes to config
# Remove this flag if you want to try continuing analysis
rule scrape:
  input: "prep.done"
  output: touch("scrape.done")
  shell:
    "isoanalyst scrape -n {NAME} -i {INPUT_SPEC} --mztol {TOL} --minscans {MINSCAN_SCRAPE} --minintensity {MININTENSITY} --restart"

# default minconditions = 1
rule analyze:
  input: "scrape.done"
  output: touch("analyze.done")
  shell:
    "isoanalyst analyze -n {NAME} -i {INPUT_SPEC} --minconditions {MINCOND} --minscans {MINSCAN_ANALYZE}"
